SRC_M = src/ft_isalpha.c src/ft_isdigit.c src/ft_isalnum.c src/ft_isascii.c src/ft_isprint.c src/ft_strlen.c src/ft_memset.c \
		src/ft_bzero.c src/ft_memcpy.c src/ft_memmove.c src/ft_strlcpy.c src/ft_strlcat.c src/ft_toupper.c src/ft_tolower.c \
		src/ft_strchr.c src/ft_strrchr.c src/ft_strncmp.c src/ft_memchr.c src/ft_memcmp.c src/ft_strnstr.c src/ft_atoi.c \
		src/ft_calloc.c src/ft_strdup.c src/ft_substr.c src/ft_strjoin.c src/ft_strtrim.c src/ft_split.c src/ft_itoa.c \
		src/ft_strmapi.c src/ft_striteri.c src/ft_putchar_fd.c src/ft_putstr_fd.c src/ft_putendl_fd.c src/ft_putnbr_fd.c

OBJ_M = $(SRC_M:.c=.o)

SRC_B = src/ft_lstnew_bonus.c src/ft_lstadd_front_bonus.c src/ft_lstsize_bonus.c src/ft_lstlast_bonus.c \
		src/ft_lstadd_back_bonus.c src/ft_lstdelone_bonus.c src/ft_lstclear_bonus.c src/ft_lstiter_bonus.c \
		src/ft_lstmap_bonus.c

OBJ_B = $(SRC_B:.c=.o)

NAME = libft.a

AR = ar rcs

CC = cc -Wall -Wextra -Werror

RM = rm -f

%.o: %.c include/libft.h
	$(CC) -c $< -Iinclude -o $@

all: $(NAME)

$(NAME): $(OBJ_M)
	$(AR) $(NAME) $(OBJ_M)

bonus: $(OBJ_M) $(OBJ_B)
	$(AR) $(NAME) $(OBJ_M) $(OBJ_B)

clean:
	$(RM) $(OBJ_M) $(OBJ_B)

fclean: clean
	$(RM) $(NAME)

re: fclean bonus